### ISSUE TITLE
Error (401 - Unauthorized)

### ISSUE THREAD

**Issue by KhaVNguyen** [repurpose/emsi-skills-api#4]
Getting the following error today when I trying to use this package:
```
401 - Unauthorized
    ^

SyntaxError: Unexpected number in JSON at position 4
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/khanguyen/Desktop/Projects/codusk-api/node_modules/emsi-skills-api/lib/api/skills.js:15:31)
    at Request.self.callback (/Users/khanguyen/Desktop/Projects/codusk-api/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:467:12)
    at Request.<anonymous> (/Users/khanguyen/Desktop/Projects/codusk-api/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:467:12)
    at IncomingMessage.<anonymous> (/Users/khanguyen/Desktop/Projects/codusk-api/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)

```

I was able to get it working fine a couple months ago. I did set `EMSI_CLIENT_ID` and `EMSI_SECRET` and I even requested new credentials.

**Comment by KhaVNguyen** [comment]
Fixed thanks!
